//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://emiage.org/", ConfigurationName="ServiceReference1.CalculsSimples")]
    public interface CalculsSimples {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/decomposerRequest", ReplyAction="http://emiage.org/CalculsSimples/decomposerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionnerResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionner))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decomposer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premierResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premier))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.ServiceReference1.decomposerResponse decomposer(WpfApplication2.ServiceReference1.decomposerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/decomposerRequest", ReplyAction="http://emiage.org/CalculsSimples/decomposerResponse")]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.decomposerResponse> decomposerAsync(WpfApplication2.ServiceReference1.decomposerRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/helloRequest", ReplyAction="http://emiage.org/CalculsSimples/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionnerResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionner))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decomposer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premierResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premier))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.ServiceReference1.helloResponse1 hello(WpfApplication2.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/helloRequest", ReplyAction="http://emiage.org/CalculsSimples/helloResponse")]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.helloResponse1> helloAsync(WpfApplication2.ServiceReference1.helloRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/additionnerRequest", ReplyAction="http://emiage.org/CalculsSimples/additionnerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionnerResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionner))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decomposer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premierResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premier))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.ServiceReference1.additionnerResponse1 additionner(WpfApplication2.ServiceReference1.additionnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/additionnerRequest", ReplyAction="http://emiage.org/CalculsSimples/additionnerResponse")]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.additionnerResponse1> additionnerAsync(WpfApplication2.ServiceReference1.additionnerRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/premierRequest", ReplyAction="http://emiage.org/CalculsSimples/premierResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionnerResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(additionner))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(decomposer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premierResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(premier))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.ServiceReference1.premierResponse1 premier(WpfApplication2.ServiceReference1.premierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://emiage.org/CalculsSimples/premierRequest", ReplyAction="http://emiage.org/CalculsSimples/premierResponse")]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.premierResponse1> premierAsync(WpfApplication2.ServiceReference1.premierRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class additionnerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class additionner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double nombreAField;
        
        private double nombreBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double nombreA {
            get {
                return this.nombreAField;
            }
            set {
                this.nombreAField = value;
                this.RaisePropertyChanged("nombreA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double nombreB {
            get {
                return this.nombreBField;
            }
            set {
                this.nombreBField = value;
                this.RaisePropertyChanged("nombreB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class decomposer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int entierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int entier {
            get {
                return this.entierField;
            }
            set {
                this.entierField = value;
                this.RaisePropertyChanged("entier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class helloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class hello : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class premierResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emiage.org/")]
    public partial class premier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int entierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int entier {
            get {
                return this.entierField;
            }
            set {
                this.entierField = value;
                this.RaisePropertyChanged("entier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decomposer", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class decomposerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entier;
        
        public decomposerRequest() {
        }
        
        public decomposerRequest(int entier) {
            this.entier = entier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decomposerResponse", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class decomposerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public decomposerResponse() {
        }
        
        public decomposerResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class helloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse1() {
        }
        
        public helloResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="additionner", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class additionnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nombreA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double nombreB;
        
        public additionnerRequest() {
        }
        
        public additionnerRequest(double nombreA, double nombreB) {
            this.nombreA = nombreA;
            this.nombreB = nombreB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="additionnerResponse", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class additionnerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public additionnerResponse1() {
        }
        
        public additionnerResponse1(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="premier", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class premierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entier;
        
        public premierRequest() {
        }
        
        public premierRequest(int entier) {
            this.entier = entier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="premierResponse", WrapperNamespace="http://emiage.org/", IsWrapped=true)]
    public partial class premierResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emiage.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public premierResponse1() {
        }
        
        public premierResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculsSimplesChannel : WpfApplication2.ServiceReference1.CalculsSimples, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculsSimplesClient : System.ServiceModel.ClientBase<WpfApplication2.ServiceReference1.CalculsSimples>, WpfApplication2.ServiceReference1.CalculsSimples {
        
        public CalculsSimplesClient() {
        }
        
        public CalculsSimplesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculsSimplesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculsSimplesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculsSimplesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.ServiceReference1.decomposerResponse WpfApplication2.ServiceReference1.CalculsSimples.decomposer(WpfApplication2.ServiceReference1.decomposerRequest request) {
            return base.Channel.decomposer(request);
        }
        
        public object[] decomposer(int entier) {
            WpfApplication2.ServiceReference1.decomposerRequest inValue = new WpfApplication2.ServiceReference1.decomposerRequest();
            inValue.entier = entier;
            WpfApplication2.ServiceReference1.decomposerResponse retVal = ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).decomposer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.decomposerResponse> WpfApplication2.ServiceReference1.CalculsSimples.decomposerAsync(WpfApplication2.ServiceReference1.decomposerRequest request) {
            return base.Channel.decomposerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.decomposerResponse> decomposerAsync(int entier) {
            WpfApplication2.ServiceReference1.decomposerRequest inValue = new WpfApplication2.ServiceReference1.decomposerRequest();
            inValue.entier = entier;
            return ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).decomposerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.ServiceReference1.helloResponse1 WpfApplication2.ServiceReference1.CalculsSimples.hello(WpfApplication2.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WpfApplication2.ServiceReference1.helloRequest inValue = new WpfApplication2.ServiceReference1.helloRequest();
            inValue.name = name;
            WpfApplication2.ServiceReference1.helloResponse1 retVal = ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.helloResponse1> WpfApplication2.ServiceReference1.CalculsSimples.helloAsync(WpfApplication2.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.helloResponse1> helloAsync(string name) {
            WpfApplication2.ServiceReference1.helloRequest inValue = new WpfApplication2.ServiceReference1.helloRequest();
            inValue.name = name;
            return ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.ServiceReference1.additionnerResponse1 WpfApplication2.ServiceReference1.CalculsSimples.additionner(WpfApplication2.ServiceReference1.additionnerRequest request) {
            return base.Channel.additionner(request);
        }
        
        public double additionner(double nombreA, double nombreB) {
            WpfApplication2.ServiceReference1.additionnerRequest inValue = new WpfApplication2.ServiceReference1.additionnerRequest();
            inValue.nombreA = nombreA;
            inValue.nombreB = nombreB;
            WpfApplication2.ServiceReference1.additionnerResponse1 retVal = ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).additionner(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.additionnerResponse1> WpfApplication2.ServiceReference1.CalculsSimples.additionnerAsync(WpfApplication2.ServiceReference1.additionnerRequest request) {
            return base.Channel.additionnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.additionnerResponse1> additionnerAsync(double nombreA, double nombreB) {
            WpfApplication2.ServiceReference1.additionnerRequest inValue = new WpfApplication2.ServiceReference1.additionnerRequest();
            inValue.nombreA = nombreA;
            inValue.nombreB = nombreB;
            return ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).additionnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.ServiceReference1.premierResponse1 WpfApplication2.ServiceReference1.CalculsSimples.premier(WpfApplication2.ServiceReference1.premierRequest request) {
            return base.Channel.premier(request);
        }
        
        public bool premier(int entier) {
            WpfApplication2.ServiceReference1.premierRequest inValue = new WpfApplication2.ServiceReference1.premierRequest();
            inValue.entier = entier;
            WpfApplication2.ServiceReference1.premierResponse1 retVal = ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).premier(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.premierResponse1> WpfApplication2.ServiceReference1.CalculsSimples.premierAsync(WpfApplication2.ServiceReference1.premierRequest request) {
            return base.Channel.premierAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.ServiceReference1.premierResponse1> premierAsync(int entier) {
            WpfApplication2.ServiceReference1.premierRequest inValue = new WpfApplication2.ServiceReference1.premierRequest();
            inValue.entier = entier;
            return ((WpfApplication2.ServiceReference1.CalculsSimples)(this)).premierAsync(inValue);
        }
    }
}
