---- Table de Dimension "CATEGORIE"

CREATE TABLE [dbo].[DIM_CATEGORIE](
	[CATEGORIE_PK] [int] 				NOT NULL,
	[LIBEL_UNIVERS] [varchar](50) 		NOT NULL,
	[ID_UNIVERS] [int] 					NOT NULL,
	[LIBEL_RAYON] [varchar](50) 		NOT NULL,
	[ID_RAYON] [int] 					NOT NULL,
	[LIBEL_FAMILLE] [varchar](50) 		NOT NULL,
	[ID_FAMILLE] [int] 					NOT NULL,
	[LIBEL_SSFAMILLE] [varchar](50) 	NOT NULL,
	[ID_SSFAMILLE] [int] 				NOT NULL,
 CONSTRAINT [PK_DIM_CATEGORIE] PRIMARY KEY CLUSTERED 
(
	[CATEGORIE_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-- Table de Fait "STOCK"

CREATE TABLE [dbo].[FACT_STOCK](
	[DATE_INVENTAIRE_FK] [int] 		NOT NULL, --FK
	[PRODUIT_FK] [int] 				NOT NULL, --FK
	[LIEU_FK] [int] 				NOT NULL, --FK
	[NBR_DISPO] [int] 				NULL,
	[NBR_DEFECTUEUX] [int] 			NULL,
	[ID_INVENTAIRE] [varchar](50) 	NULL
) ON [PRIMARY]

GO

