//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.OdeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetode.org/", ConfigurationName="OdeService.OdeService")]
    public interface OdeService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/GetCombinaisonsIndexRequest", ReplyAction="http://projetode.org/OdeService/GetCombinaisonsIndexResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.GetCombinaisonsIndexResponse GetCombinaisonsIndex(WpfApplication2.OdeService.GetCombinaisonsIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/GetCombinaisonsIndexRequest", ReplyAction="http://projetode.org/OdeService/GetCombinaisonsIndexResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsIndexResponse> GetCombinaisonsIndexAsync(WpfApplication2.OdeService.GetCombinaisonsIndexRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestGetCombinaisonsIndexRequest", ReplyAction="http://projetode.org/OdeService/TestGetCombinaisonsIndexResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse TestGetCombinaisonsIndex(WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestGetCombinaisonsIndexRequest", ReplyAction="http://projetode.org/OdeService/TestGetCombinaisonsIndexResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse> TestGetCombinaisonsIndexAsync(WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/MaterialisationPartielleRequest", ReplyAction="http://projetode.org/OdeService/MaterialisationPartielleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.MaterialisationPartielleResponse MaterialisationPartielle(WpfApplication2.OdeService.MaterialisationPartielleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/MaterialisationPartielleRequest", ReplyAction="http://projetode.org/OdeService/MaterialisationPartielleResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.MaterialisationPartielleResponse> MaterialisationPartielleAsync(WpfApplication2.OdeService.MaterialisationPartielleRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestMaterialisationPartielleRequest", ReplyAction="http://projetode.org/OdeService/TestMaterialisationPartielleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.TestMaterialisationPartielleResponse TestMaterialisationPartielle(WpfApplication2.OdeService.TestMaterialisationPartielleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestMaterialisationPartielleRequest", ReplyAction="http://projetode.org/OdeService/TestMaterialisationPartielleResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMaterialisationPartielleResponse> TestMaterialisationPartielleAsync(WpfApplication2.OdeService.TestMaterialisationPartielleRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestGetCombinaisonsRequest", ReplyAction="http://projetode.org/OdeService/TestGetCombinaisonsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.TestGetCombinaisonsResponse TestGetCombinaisons(WpfApplication2.OdeService.TestGetCombinaisonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestGetCombinaisonsRequest", ReplyAction="http://projetode.org/OdeService/TestGetCombinaisonsResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsResponse> TestGetCombinaisonsAsync(WpfApplication2.OdeService.TestGetCombinaisonsRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/GetCombinaisonsRequest", ReplyAction="http://projetode.org/OdeService/GetCombinaisonsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.GetCombinaisonsResponse GetCombinaisons(WpfApplication2.OdeService.GetCombinaisonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/GetCombinaisonsRequest", ReplyAction="http://projetode.org/OdeService/GetCombinaisonsResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsResponse> GetCombinaisonsAsync(WpfApplication2.OdeService.GetCombinaisonsRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/MetropolisRequest", ReplyAction="http://projetode.org/OdeService/MetropolisResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.MetropolisResponse Metropolis(WpfApplication2.OdeService.MetropolisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/MetropolisRequest", ReplyAction="http://projetode.org/OdeService/MetropolisResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.MetropolisResponse> MetropolisAsync(WpfApplication2.OdeService.MetropolisRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestMetropolisRequest", ReplyAction="http://projetode.org/OdeService/TestMetropolisResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication2.OdeService.TestMetropolisResponse TestMetropolis(WpfApplication2.OdeService.TestMetropolisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetode.org/OdeService/TestMetropolisRequest", ReplyAction="http://projetode.org/OdeService/TestMetropolisResponse")]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMetropolisResponse> TestMetropolisAsync(WpfApplication2.OdeService.TestMetropolisRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://projetode.org/")]
    public partial class dimension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dimensionNameField;
        
        private long dimensionCountField;
        
        private int dimensionMemoryField;
        
        private int dimensionOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dimensionName {
            get {
                return this.dimensionNameField;
            }
            set {
                this.dimensionNameField = value;
                this.RaisePropertyChanged("dimensionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long dimensionCount {
            get {
                return this.dimensionCountField;
            }
            set {
                this.dimensionCountField = value;
                this.RaisePropertyChanged("dimensionCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dimensionMemory {
            get {
                return this.dimensionMemoryField;
            }
            set {
                this.dimensionMemoryField = value;
                this.RaisePropertyChanged("dimensionMemory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dimensionOrder {
            get {
                return this.dimensionOrderField;
            }
            set {
                this.dimensionOrderField = value;
                this.RaisePropertyChanged("dimensionOrder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCombinaisonsIndex", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class GetCombinaisonsIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplication2.OdeService.dimension[] arg0;
        
        public GetCombinaisonsIndexRequest() {
        }
        
        public GetCombinaisonsIndexRequest(WpfApplication2.OdeService.dimension[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCombinaisonsIndexResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class GetCombinaisonsIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GetCombinaisonsIndexResponse() {
        }
        
        public GetCombinaisonsIndexResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestGetCombinaisonsIndex", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestGetCombinaisonsIndexRequest {
        
        public TestGetCombinaisonsIndexRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestGetCombinaisonsIndexResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestGetCombinaisonsIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public TestGetCombinaisonsIndexResponse() {
        }
        
        public TestGetCombinaisonsIndexResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MaterialisationPartielle", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class MaterialisationPartielleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplication2.OdeService.dimension[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        public MaterialisationPartielleRequest() {
        }
        
        public MaterialisationPartielleRequest(WpfApplication2.OdeService.dimension[] arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MaterialisationPartielleResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class MaterialisationPartielleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public MaterialisationPartielleResponse() {
        }
        
        public MaterialisationPartielleResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestMaterialisationPartielle", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestMaterialisationPartielleRequest {
        
        public TestMaterialisationPartielleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestMaterialisationPartielleResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestMaterialisationPartielleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public TestMaterialisationPartielleResponse() {
        }
        
        public TestMaterialisationPartielleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestGetCombinaisons", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestGetCombinaisonsRequest {
        
        public TestGetCombinaisonsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestGetCombinaisonsResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestGetCombinaisonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public TestGetCombinaisonsResponse() {
        }
        
        public TestGetCombinaisonsResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCombinaisons", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class GetCombinaisonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplication2.OdeService.dimension[] arg0;
        
        public GetCombinaisonsRequest() {
        }
        
        public GetCombinaisonsRequest(WpfApplication2.OdeService.dimension[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCombinaisonsResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class GetCombinaisonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplication2.OdeService.dimension[] @return;
        
        public GetCombinaisonsResponse() {
        }
        
        public GetCombinaisonsResponse(WpfApplication2.OdeService.dimension[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Metropolis", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class MetropolisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplication2.OdeService.dimension[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public MetropolisRequest() {
        }
        
        public MetropolisRequest(WpfApplication2.OdeService.dimension[] arg0, double arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MetropolisResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class MetropolisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public MetropolisResponse() {
        }
        
        public MetropolisResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestMetropolis", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestMetropolisRequest {
        
        public TestMetropolisRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestMetropolisResponse", WrapperNamespace="http://projetode.org/", IsWrapped=true)]
    public partial class TestMetropolisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://projetode.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public TestMetropolisResponse() {
        }
        
        public TestMetropolisResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdeServiceChannel : WpfApplication2.OdeService.OdeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdeServiceClient : System.ServiceModel.ClientBase<WpfApplication2.OdeService.OdeService>, WpfApplication2.OdeService.OdeService {
        
        public OdeServiceClient() {
        }
        
        public OdeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.GetCombinaisonsIndexResponse WpfApplication2.OdeService.OdeService.GetCombinaisonsIndex(WpfApplication2.OdeService.GetCombinaisonsIndexRequest request) {
            return base.Channel.GetCombinaisonsIndex(request);
        }
        
        public string[] GetCombinaisonsIndex(WpfApplication2.OdeService.dimension[] arg0) {
            WpfApplication2.OdeService.GetCombinaisonsIndexRequest inValue = new WpfApplication2.OdeService.GetCombinaisonsIndexRequest();
            inValue.arg0 = arg0;
            WpfApplication2.OdeService.GetCombinaisonsIndexResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).GetCombinaisonsIndex(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsIndexResponse> WpfApplication2.OdeService.OdeService.GetCombinaisonsIndexAsync(WpfApplication2.OdeService.GetCombinaisonsIndexRequest request) {
            return base.Channel.GetCombinaisonsIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsIndexResponse> GetCombinaisonsIndexAsync(WpfApplication2.OdeService.dimension[] arg0) {
            WpfApplication2.OdeService.GetCombinaisonsIndexRequest inValue = new WpfApplication2.OdeService.GetCombinaisonsIndexRequest();
            inValue.arg0 = arg0;
            return ((WpfApplication2.OdeService.OdeService)(this)).GetCombinaisonsIndexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse WpfApplication2.OdeService.OdeService.TestGetCombinaisonsIndex(WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest request) {
            return base.Channel.TestGetCombinaisonsIndex(request);
        }
        
        public bool TestGetCombinaisonsIndex() {
            WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest inValue = new WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest();
            WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).TestGetCombinaisonsIndex(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse> WpfApplication2.OdeService.OdeService.TestGetCombinaisonsIndexAsync(WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest request) {
            return base.Channel.TestGetCombinaisonsIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsIndexResponse> TestGetCombinaisonsIndexAsync() {
            WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest inValue = new WpfApplication2.OdeService.TestGetCombinaisonsIndexRequest();
            return ((WpfApplication2.OdeService.OdeService)(this)).TestGetCombinaisonsIndexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.MaterialisationPartielleResponse WpfApplication2.OdeService.OdeService.MaterialisationPartielle(WpfApplication2.OdeService.MaterialisationPartielleRequest request) {
            return base.Channel.MaterialisationPartielle(request);
        }
        
        public int[] MaterialisationPartielle(WpfApplication2.OdeService.dimension[] arg0, double arg1) {
            WpfApplication2.OdeService.MaterialisationPartielleRequest inValue = new WpfApplication2.OdeService.MaterialisationPartielleRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WpfApplication2.OdeService.MaterialisationPartielleResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).MaterialisationPartielle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.MaterialisationPartielleResponse> WpfApplication2.OdeService.OdeService.MaterialisationPartielleAsync(WpfApplication2.OdeService.MaterialisationPartielleRequest request) {
            return base.Channel.MaterialisationPartielleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.MaterialisationPartielleResponse> MaterialisationPartielleAsync(WpfApplication2.OdeService.dimension[] arg0, double arg1) {
            WpfApplication2.OdeService.MaterialisationPartielleRequest inValue = new WpfApplication2.OdeService.MaterialisationPartielleRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WpfApplication2.OdeService.OdeService)(this)).MaterialisationPartielleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.TestMaterialisationPartielleResponse WpfApplication2.OdeService.OdeService.TestMaterialisationPartielle(WpfApplication2.OdeService.TestMaterialisationPartielleRequest request) {
            return base.Channel.TestMaterialisationPartielle(request);
        }
        
        public bool TestMaterialisationPartielle() {
            WpfApplication2.OdeService.TestMaterialisationPartielleRequest inValue = new WpfApplication2.OdeService.TestMaterialisationPartielleRequest();
            WpfApplication2.OdeService.TestMaterialisationPartielleResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).TestMaterialisationPartielle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMaterialisationPartielleResponse> WpfApplication2.OdeService.OdeService.TestMaterialisationPartielleAsync(WpfApplication2.OdeService.TestMaterialisationPartielleRequest request) {
            return base.Channel.TestMaterialisationPartielleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMaterialisationPartielleResponse> TestMaterialisationPartielleAsync() {
            WpfApplication2.OdeService.TestMaterialisationPartielleRequest inValue = new WpfApplication2.OdeService.TestMaterialisationPartielleRequest();
            return ((WpfApplication2.OdeService.OdeService)(this)).TestMaterialisationPartielleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.TestGetCombinaisonsResponse WpfApplication2.OdeService.OdeService.TestGetCombinaisons(WpfApplication2.OdeService.TestGetCombinaisonsRequest request) {
            return base.Channel.TestGetCombinaisons(request);
        }
        
        public bool TestGetCombinaisons() {
            WpfApplication2.OdeService.TestGetCombinaisonsRequest inValue = new WpfApplication2.OdeService.TestGetCombinaisonsRequest();
            WpfApplication2.OdeService.TestGetCombinaisonsResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).TestGetCombinaisons(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsResponse> WpfApplication2.OdeService.OdeService.TestGetCombinaisonsAsync(WpfApplication2.OdeService.TestGetCombinaisonsRequest request) {
            return base.Channel.TestGetCombinaisonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.TestGetCombinaisonsResponse> TestGetCombinaisonsAsync() {
            WpfApplication2.OdeService.TestGetCombinaisonsRequest inValue = new WpfApplication2.OdeService.TestGetCombinaisonsRequest();
            return ((WpfApplication2.OdeService.OdeService)(this)).TestGetCombinaisonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.GetCombinaisonsResponse WpfApplication2.OdeService.OdeService.GetCombinaisons(WpfApplication2.OdeService.GetCombinaisonsRequest request) {
            return base.Channel.GetCombinaisons(request);
        }
        
        public WpfApplication2.OdeService.dimension[] GetCombinaisons(WpfApplication2.OdeService.dimension[] arg0) {
            WpfApplication2.OdeService.GetCombinaisonsRequest inValue = new WpfApplication2.OdeService.GetCombinaisonsRequest();
            inValue.arg0 = arg0;
            WpfApplication2.OdeService.GetCombinaisonsResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).GetCombinaisons(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsResponse> WpfApplication2.OdeService.OdeService.GetCombinaisonsAsync(WpfApplication2.OdeService.GetCombinaisonsRequest request) {
            return base.Channel.GetCombinaisonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.GetCombinaisonsResponse> GetCombinaisonsAsync(WpfApplication2.OdeService.dimension[] arg0) {
            WpfApplication2.OdeService.GetCombinaisonsRequest inValue = new WpfApplication2.OdeService.GetCombinaisonsRequest();
            inValue.arg0 = arg0;
            return ((WpfApplication2.OdeService.OdeService)(this)).GetCombinaisonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.MetropolisResponse WpfApplication2.OdeService.OdeService.Metropolis(WpfApplication2.OdeService.MetropolisRequest request) {
            return base.Channel.Metropolis(request);
        }
        
        public int[] Metropolis(WpfApplication2.OdeService.dimension[] arg0, double arg1, int arg2) {
            WpfApplication2.OdeService.MetropolisRequest inValue = new WpfApplication2.OdeService.MetropolisRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            WpfApplication2.OdeService.MetropolisResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).Metropolis(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.MetropolisResponse> WpfApplication2.OdeService.OdeService.MetropolisAsync(WpfApplication2.OdeService.MetropolisRequest request) {
            return base.Channel.MetropolisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.MetropolisResponse> MetropolisAsync(WpfApplication2.OdeService.dimension[] arg0, double arg1, int arg2) {
            WpfApplication2.OdeService.MetropolisRequest inValue = new WpfApplication2.OdeService.MetropolisRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((WpfApplication2.OdeService.OdeService)(this)).MetropolisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.OdeService.TestMetropolisResponse WpfApplication2.OdeService.OdeService.TestMetropolis(WpfApplication2.OdeService.TestMetropolisRequest request) {
            return base.Channel.TestMetropolis(request);
        }
        
        public bool TestMetropolis() {
            WpfApplication2.OdeService.TestMetropolisRequest inValue = new WpfApplication2.OdeService.TestMetropolisRequest();
            WpfApplication2.OdeService.TestMetropolisResponse retVal = ((WpfApplication2.OdeService.OdeService)(this)).TestMetropolis(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMetropolisResponse> WpfApplication2.OdeService.OdeService.TestMetropolisAsync(WpfApplication2.OdeService.TestMetropolisRequest request) {
            return base.Channel.TestMetropolisAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.OdeService.TestMetropolisResponse> TestMetropolisAsync() {
            WpfApplication2.OdeService.TestMetropolisRequest inValue = new WpfApplication2.OdeService.TestMetropolisRequest();
            return ((WpfApplication2.OdeService.OdeService)(this)).TestMetropolisAsync(inValue);
        }
    }
}
