//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.WSOptimiseur {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://miage.org/", ConfigurationName="WSOptimiseur.WSOptimODE")]
    public interface WSOptimODE {
        
        // CODEGEN: Generating message contract since element name prefix from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://miage.org/WSOptimODE/operationRequest", ReplyAction="http://miage.org/WSOptimODE/operationResponse")]
        WpfApplication2.WSOptimiseur.operationResponse operation(WpfApplication2.WSOptimiseur.operationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miage.org/WSOptimODE/operationRequest", ReplyAction="http://miage.org/WSOptimODE/operationResponse")]
        System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.operationResponse> operationAsync(WpfApplication2.WSOptimiseur.operationRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://miage.org/WSOptimODE/helloRequest", ReplyAction="http://miage.org/WSOptimODE/helloResponse")]
        WpfApplication2.WSOptimiseur.helloResponse hello(WpfApplication2.WSOptimiseur.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://miage.org/WSOptimODE/helloRequest", ReplyAction="http://miage.org/WSOptimODE/helloResponse")]
        System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.helloResponse> helloAsync(WpfApplication2.WSOptimiseur.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operation", Namespace="http://miage.org/", Order=0)]
        public WpfApplication2.WSOptimiseur.operationRequestBody Body;
        
        public operationRequest() {
        }
        
        public operationRequest(WpfApplication2.WSOptimiseur.operationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int profCourante;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int rang;
        
        public operationRequestBody() {
        }
        
        public operationRequestBody(int profCourante, string prefix, int rang) {
            this.profCourante = profCourante;
            this.prefix = prefix;
            this.rang = rang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operationResponse", Namespace="http://miage.org/", Order=0)]
        public WpfApplication2.WSOptimiseur.operationResponseBody Body;
        
        public operationResponse() {
        }
        
        public operationResponse(WpfApplication2.WSOptimiseur.operationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public operationResponseBody() {
        }
        
        public operationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://miage.org/", Order=0)]
        public WpfApplication2.WSOptimiseur.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(WpfApplication2.WSOptimiseur.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://miage.org/", Order=0)]
        public WpfApplication2.WSOptimiseur.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(WpfApplication2.WSOptimiseur.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOptimODEChannel : WpfApplication2.WSOptimiseur.WSOptimODE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOptimODEClient : System.ServiceModel.ClientBase<WpfApplication2.WSOptimiseur.WSOptimODE>, WpfApplication2.WSOptimiseur.WSOptimODE {
        
        public WSOptimODEClient() {
        }
        
        public WSOptimODEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOptimODEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOptimODEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOptimODEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.WSOptimiseur.operationResponse WpfApplication2.WSOptimiseur.WSOptimODE.operation(WpfApplication2.WSOptimiseur.operationRequest request) {
            return base.Channel.operation(request);
        }
        
        public string operation(int profCourante, string prefix, int rang) {
            WpfApplication2.WSOptimiseur.operationRequest inValue = new WpfApplication2.WSOptimiseur.operationRequest();
            inValue.Body = new WpfApplication2.WSOptimiseur.operationRequestBody();
            inValue.Body.profCourante = profCourante;
            inValue.Body.prefix = prefix;
            inValue.Body.rang = rang;
            WpfApplication2.WSOptimiseur.operationResponse retVal = ((WpfApplication2.WSOptimiseur.WSOptimODE)(this)).operation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.operationResponse> WpfApplication2.WSOptimiseur.WSOptimODE.operationAsync(WpfApplication2.WSOptimiseur.operationRequest request) {
            return base.Channel.operationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.operationResponse> operationAsync(int profCourante, string prefix, int rang) {
            WpfApplication2.WSOptimiseur.operationRequest inValue = new WpfApplication2.WSOptimiseur.operationRequest();
            inValue.Body = new WpfApplication2.WSOptimiseur.operationRequestBody();
            inValue.Body.profCourante = profCourante;
            inValue.Body.prefix = prefix;
            inValue.Body.rang = rang;
            return ((WpfApplication2.WSOptimiseur.WSOptimODE)(this)).operationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication2.WSOptimiseur.helloResponse WpfApplication2.WSOptimiseur.WSOptimODE.hello(WpfApplication2.WSOptimiseur.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WpfApplication2.WSOptimiseur.helloRequest inValue = new WpfApplication2.WSOptimiseur.helloRequest();
            inValue.Body = new WpfApplication2.WSOptimiseur.helloRequestBody();
            inValue.Body.name = name;
            WpfApplication2.WSOptimiseur.helloResponse retVal = ((WpfApplication2.WSOptimiseur.WSOptimODE)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.helloResponse> WpfApplication2.WSOptimiseur.WSOptimODE.helloAsync(WpfApplication2.WSOptimiseur.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication2.WSOptimiseur.helloResponse> helloAsync(string name) {
            WpfApplication2.WSOptimiseur.helloRequest inValue = new WpfApplication2.WSOptimiseur.helloRequest();
            inValue.Body = new WpfApplication2.WSOptimiseur.helloRequestBody();
            inValue.Body.name = name;
            return ((WpfApplication2.WSOptimiseur.WSOptimODE)(this)).helloAsync(inValue);
        }
    }
}
